const LINKS = {
  promo1: "link",
  promo2: "link",
  promo3: "link",
  promo4: "link",
  promo5: "link",
  promo6: "link",
  promo7: "link",
  promo8: "link",
  promo9: "link",
  promo10: "link",
  promo11: "link",
  promo12: "link",
  promo13: "link",
  promo14: "link",
  promo15: "link",
  promo16: "link",
  promo17: "link",
  promo18: "link"
  promo19: "link",
  promo20: "link",
};
